# Generated by Django 6.0.3 on 2026-03-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('phone_number', 'campaign')},
        ),
    ]
