# Generated by Django 6.0.3 on 2026-03-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_alter_contact_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='buttons',
            field=models.JSONField(default=list),
        ),
    ]
