# Generated by Django 6.0.3 on 2026-03-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_campaign_status'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reply',
            constraint=models.UniqueConstraint(fields=('phone_number', 'campaign', 'response'), name='unique_reply_once'),
        ),
    ]
