# Generated by Django 6.0.3 on 2026-03-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_reply_unique_reply_once'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='image_path',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='media_id',
        ),
        migrations.AddField(
            model_name='campaign',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='twilio_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
