# Generated by Django 6.0.3 on 2026-03-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_remove_campaign_image_path_remove_campaign_media_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='twilio_sid',
        ),
        migrations.AddField(
            model_name='contact',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
