# Generated by Django 6.0.3 on 2026-03-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0008_remove_contact_twilio_sid_contact_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
