# Generated by Django 6.0.3 on 2026-03-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0009_alter_contact_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='template_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='variables',
            field=models.JSONField(default=list),
        ),
    ]
