# Generated by Django 6.0.3 on 2026-03-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0010_campaign_template_name_campaign_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='message_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
